Event registration
ZAINABFATIMA0/Eventify pull request #6
Opened 2024-07-30 08:05 UTC by ZAINABFATIMA0

Added registration in events through email verification,

2024-07-30 14:36 UTC, ChaudharyHamza65Chaudhary786 approved these changes

2024-07-31 07:03 UTC, sheralim012 requested changes

2024-07-31 07:03 UTC, sheralim012 commented on eventify/settings.py
> +CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
Value for this should be coming from env variable

2024-07-31 07:03 UTC, sheralim012 commented on Readme.md
> +```
is this instruction necessary?, as the codebase has already this info

2024-07-31 07:03 UTC, sheralim012 commented on Readme.md
> +Add the following Celery settings in your settings.py:
the value for celery broker url should come from env variable

2024-07-31 07:03 UTC, sheralim012 commented on users/serializer.py
> +        registration, created = Registration.objects.update_or_create(
add validation for if registration form is open

2024-07-31 07:03 UTC, sheralim012 commented on users/serializer.py
> +                'otp_expiry': timezone.now() + timedelta(minutes=5)
timedelta value should be configurable

2024-07-31 07:03 UTC, sheralim012 commented on events/views.py
> +
```suggestion
 
 
```

2024-07-31 07:03 UTC, sheralim012 commented on events/views.py
> +            'event': pk
why not pass whole data object from request?

2024-07-31 07:03 UTC, sheralim012 commented on events/views.py
> +    return Response({"message": "Registration created successfully. Email is not verified"})
update msg to indicate that check your email for OTP

2024-07-31 07:03 UTC, sheralim012 commented on events/views.py
> +    registration.otp = None
reset opt expiry as well

2024-07-31 07:03 UTC, sheralim012 commented on events/views.py
> +    registration.save()
if small set of fields are updated then it's recommended to use update_fields in save as it's more performant

2024-07-31 11:35 UTC, sheralim012 approved these changes

2024-07-31 11:38 UTC, merged